import { InsertUserSunscreen } from '@/lib/userSunscreen'
import { Asset } from 'expo-asset'

const resolveDevImage = (module: number): string => Asset.fromModule(module).uri

export const getUserSunscreenData = (userId: string): InsertUserSunscreen[] => [
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Daily Face',
    is_favorite: 0,
    notes: null,
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_1.jpg')),
    name: 'Ultra Sheer Dry-Touch',
    brand: 'Neutrogena',
    spf: 100,
    type: 'chemical',
    form: 'lotion',
    coverage: 'face',
    duration: 15000,
    water_duration: null,
    barcode: '070501101056',
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: null,
    is_favorite: 0,
    notes: null,
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_2.png')),
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    spf: 50,
    type: 'chemical',
    form: 'gel',
    coverage: 'face',
    duration: 30000,
    water_duration: null,
    barcode: '041167052419',
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Sensitive Skin 1',
    is_favorite: 0,
    notes: 'Saturdays for practice',
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_3.jpeg')),
    name: 'Mineral Sunscreen',
    brand: 'Coppertone',
    spf: 50,
    type: 'mineral',
    form: 'lotion',
    coverage: 'body',
    duration: 7200000,
    water_duration: 7200003,
    barcode: null,
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Sensitive Skin 2',
    is_favorite: 0,
    notes: 'Saturdays for practice',
    image_uri: null,
    name: 'Mineral Sunscreen',
    brand: 'Coppertone',
    spf: 50,
    type: 'mineral',
    form: 'lotion',
    coverage: 'body',
    duration: 14400000,
    water_duration: 7200000,
    barcode: '052800611902',
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Beach Spray 3',
    is_favorite: 0,
    notes: null,
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_5.webp')),
    name: 'Sport Continuous Spray',
    brand: 'Banana Boat',
    spf: 70,
    type: 'chemical',
    form: 'spray',
    coverage: 'body',
    duration: 7200000,
    water_duration: 7200000,
    barcode: null,
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Lip & Nose 4',
    is_favorite: 0,
    notes: null,
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_6.webp')),
    name: 'Invisible Zinc Stick',
    brand: 'EltaMD',
    spf: 50,
    type: 'mineral',
    form: 'stick',
    coverage: 'lip',
    duration: 5400000,
    water_duration: 5400000,
    barcode: '012044009517',
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Kids',
    is_favorite: 0,
    notes:
      'Say, How you doing? You know Im fine Worried about me, dont waste your time Made my own choices so I can sleep at night No one ever looking out or wanna see me shine So when I walk in this shit, then you know it Im feeling alive, I cant show it, no',
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_7.jpg')),
    name: 'Anthelios Melt-in Milk Sunscreen',
    brand: 'La Roche-Posay',
    spf: 60,
    type: 'hybrid',
    form: 'lotion',
    coverage: 'body',
    duration: 7200000,
    water_duration: 7200000,
    barcode: '654207702263',
  },
  {
    user_id: userId,
    sunscreen_id: null,
    nickname: 'Kids Lip & Nose Lip & Nose Lip & Nose',
    is_favorite: 0,
    notes:
      'Say, How you doing? You know Im fine Worried about me, dont waste your time Made my own choices so I can sleep at night No one ever looking out or wanna see me shine So when I walk in this shit, then you know it Im feeling alive, I cant show it, no',
    image_uri: resolveDevImage(require('@/assets/dev/images/sunscreen_7.jpg')),
    name: 'Anthelios Melt-in Milk Sunscreen Anthelios Melt-in Milk Sunscreen Anthelios Melt-in Milk Sunscreen',
    brand: 'La Roche-Posay La Roche-Posay La Roche-Posay',
    spf: 60,
    type: 'hybrid',
    form: 'lotion',
    coverage: 'body',
    duration: 7200000,
    water_duration: 7200000,
    barcode: '654207702263',
  },
]


export const getUserSunscreenPlaceholder = (userId: string): InsertUserSunscreen => {
  return {
    user_id: userId,
    sunscreen_id: null,
    nickname: '[placeholder]',
    is_favorite: 0,
    notes: '[placeholder]',
    image_uri: null,
    name: '[placeholder]',
    brand: '[placeholder]',
    spf: 30,
    type: null,
    form: null,
    coverage: null,
    duration: 120,
    water_duration: null,
    barcode: null,
  }
}
